//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCLScholarWeb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Announcement()
        {
            this.AnnouncementResources = new HashSet<AnnouncementResource>();
        }
    
        public int AnnouncementID { get; set; }
        public string AnnouncementContent { get; set; }
        public string UserID { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string Status { get; set; }
        public string AnnouncementSubject { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnnouncementResource> AnnouncementResources { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
