//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCLScholarWeb.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lipatdbEntities : DbContext
    {
        public lipatdbEntities()
            : base("name=lipatdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AdminAuditLog> AdminAuditLogs { get; set; }
        public virtual DbSet<AnnouncementResource> AnnouncementResources { get; set; }
        public virtual DbSet<Announcement> Announcements { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<FileLocationStorage> FileLocationStorages { get; set; }
        public virtual DbSet<Form> Forms { get; set; }
        public virtual DbSet<FormsResource> FormsResources { get; set; }
        public virtual DbSet<Parent> Parents { get; set; }
        public virtual DbSet<PreValidatedStudent> PreValidatedStudents { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<RequestResource> RequestResources { get; set; }
        public virtual DbSet<Scholarship> Scholarships { get; set; }
        public virtual DbSet<ScholarshipType> ScholarshipTypes { get; set; }
        public virtual DbSet<SiblingDiscount> SiblingDiscounts { get; set; }
        public virtual DbSet<StudentProfile> StudentProfiles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<UserProgram> UserPrograms { get; set; }
        public virtual DbSet<ValidationPeriod> ValidationPeriods { get; set; }
        public virtual DbSet<ValidationRequest> ValidationRequests { get; set; }
        public virtual DbSet<ValidationStatu> ValidationStatus { get; set; }
        public virtual DbSet<WebSetting> WebSettings { get; set; }
    }
}
