//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCLScholarWeb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scholarship
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Scholarship()
        {
            this.PreValidatedStudents = new HashSet<PreValidatedStudent>();
            this.ValidationRequests = new HashSet<ValidationRequest>();
        }
    
        public int ScholarshipID { get; set; }
        public string ScholarshipName { get; set; }
        public string ScholarshipDescription { get; set; }
        public bool ApplicationForm { get; set; }
        public int PeriodID { get; set; }
        public int ScholarshipTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreValidatedStudent> PreValidatedStudents { get; set; }
        public virtual ScholarshipType ScholarshipType { get; set; }
        public virtual ValidationPeriod ValidationPeriod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValidationRequest> ValidationRequests { get; set; }
    }
}
