//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCLScholarWeb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProgram
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public int ProgramID { get; set; }
        public int Year { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Program Program { get; set; }
    }
}
