//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCLScholarWeb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValidationRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ValidationRequest()
        {
            this.RequestResources = new HashSet<RequestResource>();
            this.SiblingDiscounts = new HashSet<SiblingDiscount>();
        }
    
        public int RequestID { get; set; }
        public string UserID { get; set; }
        public int ScholarshipID { get; set; }
        public int StatusID { get; set; }
        public int PeriodID { get; set; }
        public System.DateTime DateFilled { get; set; }
        public string Remarks { get; set; }
        public bool Processed { get; set; }
        public System.DateTime DateEvaluated { get; set; }
        public string AdminID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestResource> RequestResources { get; set; }
        public virtual Scholarship Scholarship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiblingDiscount> SiblingDiscounts { get; set; }
        public virtual ValidationPeriod ValidationPeriod { get; set; }
        public virtual ValidationStatu ValidationStatu { get; set; }
    }
}
